name: Test
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_ruby_and_rails_versions:
    runs-on: ubuntu-20.04

    continue-on-error: ${{ matrix.allow_failures || false }}

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}" ### allows adding gemfile: to the matrix, bundler will automatically pick this up

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.4
            RAILS_VERSION: "4.2"

          - ruby: 2.5
            RAILS_VERSION: "5.0"

          - ruby: 2.5
            RAILS_VERSION: "5.1"

          - ruby: 2.6
            RAILS_VERSION: "5.2"

          - ruby: 2.7
            RAILS_VERSION: "6.0"

#          - ruby: "3.0" ### must be quoted otherwise will be treated as "3" which resolves to latest 3.x version
#            RAILS_VERSION: "7.0"

    steps:
      - uses: actions/checkout@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: "${{ matrix.RAILS_VERSION != 4.2 }}"

      - name: Run tests
        run: |
          export RAILS_VERSION=${{ matrix.RAILS_VERSION }}
          spec/ci.rb
